### PR TITLE
DOCS: fix grammar

### PR DESCRIPTION
**Pull request by verbose117**
Fix grammar in docs

### CODE REVIEW

**Comment by techyminati** [comment]
Bruh, the spelling is correct. lunch is build command, from which you call for a specific device makefile.

**Comment by adithya-s-sekhar** [comment]
lunch is an actual command: https://source.android.com/setup/build/building#lunch

**Comment by agam778** [comment]
Uh, that's totally correct though.

**Comment by lordarcadius** [comment]
Peak contribution

**Comment by ArixElo** [comment]
bruhhhh, that's the AOSP command for building.

**Comment by abhiawatade** [comment]
😂

**Comment by 0x8008** [comment]
You still did a better job than Nothing did with their QC so far

**Comment by MadmoudRMX2020** [comment]
Damn. Teach how to becum pro wen? You really made a big contribution there by being VERY smart 😂
There's a reason why breakfast command exists, protip: stay away from Android

**Comment by GhostMaster69-dev** [comment]
> Fix grammar in docs

Troll them on twitter for not merging your pull request but I will join you only after my lunch bye.

**Comment by vinaytiparadi** [comment]
> Fix grammar in docs

have a look at this: https://source.android.com/setup/build/building

**Comment by DarkPlayerr** [comment]
nothing needs to hire you

**Comment by 100Daisy** [comment]
I once did a meme issue on github, however i was lucky and not landed on github retards

**Comment by iamthecloverly** [comment]
Lmao dead 🤣

**Comment by ghost** [comment]
Guiness World record waiting for you 🤣🤣

**Comment by fosslover69** [comment]
I apologize for my terrible English in advance; it's not my native tongue. So please, bear with me for every foolish mistake I would make throughout the entirety of this conversation.
I'd like to interject for a moment, What you are referring to Grammar here is technically a typo (according to your logic). Grammar mistakes are mistakes that happen while using improper nouns, Verb, Adverb, Adjective, Tense, Prepositions, Articles, etc.
For example, You could have corrected that sentence to _Please make sure the path of vendor_links is correct when you lunch and **build the** image_
For your information, What you have corrected here is a reference to the AOSP build command ``` lunch```. For More Information check [here](https://source.android.com/setup/build/building#lunch), Not a Typo.

**Comment by raveen2k3** [comment]
Good effort fr 🤗

**Comment by Sushrut1101** [comment]
Wtf it's correct

**Comment by w1zzyl** [comment]
Why so pro, when Nothing will learn from this guy?

**Comment by falasyam** [comment]
🤣🤣🤣

**Comment by SunnyRaj84348** [comment]
Nice.

**Comment by verbose117** [comment]
Wow 😂! I didn't know that lunch was a build command. anyway this thing has got fired up lmao 🤣!

BTW thanks for the new knowledge and the criticisms 😄

**Pull request closed without merging**
